In [2]:
import csv
import random
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import mean_squared_error

from subprocess import check_output
print(check_output(["ls", "/Users/Hermione/MasterUCL/Web economics/Assignment/dataset"]).decode("utf8"))

cleantest.csv
cleantrain.csv
cleanvalidation.csv
test.csv
train.csv
validation.csv

In [3]:
train = pd.read_csv("/Users/Hermione/MasterUCL/Web economics/Assignment/dataset/train.csv")
#test = pd.read_csv("/Users/Hermione/MasterUCL/Web economics/Assignment/dataset/test.csv")
validation = pd.read_csv("/Users/Hermione/MasterUCL/Web economics/Assignment/dataset/validation.csv")

# Data Exlporation

In [4]:
train.columns

Index(['click', 'weekday', 'hour', 'bidid', 'logtype', 'userid', 'useragent',
       'IP', 'region', 'city', 'adexchange', 'domain', 'url', 'urlid',
       'slotid', 'slotwidth', 'slotheight', 'slotvisibility', 'slotformat',
       'slotprice', 'creative', 'bidprice', 'payprice', 'keypage',
       'advertiser', 'usertag'],
      dtype='object')

In [5]:
df = pd.DataFrame()
df['advertiser'] = np.sort(train.advertiser.unique())
df['impressions'] = train.groupby('advertiser').size().values
df['click'] = train.groupby('advertiser').click.aggregate(np.sum).values
df['cost'] = train.groupby('advertiser').payprice.aggregate(np.sum).values
df['CTR'] = (((df.click / df.impressions) * 100).round(2)).astype(str) + '%'
df['CPM'] = (((df.cost / df.impressions) * 1000).round(2)).astype(str)
df['eCPC'] = ((df.cost / df.click).round(2)).astype(str)

df

   advertiser  impressions  click      cost    CTR       CPM       eCPC
0        1458       540293    451  37231239  0.08%  68909.35   82552.64
1        2259       146778     45  13649026  0.03%  92990.95  303311.69
2        2261       120619     37  10789152  0.03%   89448.2   291598.7
3        2821       231416    144  20625766  0.06%  89128.52  143234.49
4        2997        54487    251   3413227  0.46%  62642.96   13598.51
5        3358       304782    233  28145288  0.08%  92345.64  120795.23
6        3386       498554    358  38341028  0.07%  76904.46  107097.84
7        3427       454031    340  36820111  0.07%  81096.03  108294.44
8        3476       346778    175  27481402  0.05%  79247.82  157036.58

In [6]:
def CTR(variable):
    df = pd.DataFrame()
    df[variable] = np.sort(train[variable].unique())
    df['impressions'] = train.groupby(variable).size().values
    df['click'] = train.groupby(variable).click.aggregate(np.sum).values
    df['CTR'] = (((df.click / df.impressions) * 100).round(2)).astype(str) + '%'
    
    return df.sort_values(["CTR"],ascending = False)

In [7]:
CTR("weekday")

   weekday  impressions  click    CTR
2        2       328051    298  0.09%
3        3       380111    345  0.09%
4        4       361376    311  0.09%
5        5       378028    299  0.08%
1        1       408417    277  0.07%
0        0       465241    293  0.06%
6        6       376514    211  0.06%

In [9]:
CTR("hour")

    hour  impressions  click    CTR
21    21       112438    118   0.1%
18    18       171748    171   0.1%
17    17       159044    154   0.1%
23    23       126138    113  0.09%
2      2        38384     33  0.09%
22    22       172076    147  0.09%
19    19       132278    118  0.09%
16    16       166315    129  0.08%
20    20       134229    101  0.08%
0      0       202239    164  0.08%
13    13       155792    115  0.07%
15    15       166252    123  0.07%
7      7        51105     38  0.07%
10    10       140537     78  0.06%
1      1        66660     41  0.06%
14    14       145782     93  0.06%
6      6        25624     16  0.06%
3      3        36754     21  0.06%
11    11       143110     77  0.05%
9      9        90397     48  0.05%
8      8        76370     41  0.05%
5      5        21748     11  0.05%
12    12       142075     75  0.05%
4      4        20643      9  0.04%

In [10]:
CTR("adexchange")

  adexchange  impressions  click    CTR
4       null        54487    251  0.46%
0          1       815403    658  0.08%
2          3       900222    641  0.07%
1          2       840105    436  0.05%
3          4        87521     48  0.05%

In [11]:
CTR("useragent").head(10)

         useragent  impressions  click    CTR
5    android_other         1956     13  0.66%
0   android_chrome          510      3  0.59%
6   android_safari        67728    326  0.48%
9       ios_safari          433      2  0.46%
21       mac_other         8700     31  0.36%
22      mac_safari        41409    140  0.34%
11   linux_firefox          414      1  0.24%
10    linux_chrome         1060      2  0.19%
28     other_other         1788      2  0.11%
34   windows_opera         2434      2  0.08%

In [12]:
CTR("region").head(10)

    region  impressions  click    CTR
30     368         9862     14  0.14%
0        0        56868     61  0.11%
33     394         7458      8  0.11%
26     325          942      1  0.11%
18     201        71649     61  0.09%
32     393        14832     14  0.09%
4       15        70365     62  0.09%
27     333        74289     65  0.09%
8       65        56456     52  0.09%
24     298        27417     24  0.09%

In [13]:
CTR("city").head(10)

     city  impressions  click    CTR
333   359          148      2  1.35%
368   398          217      1  0.46%
288   314          789      3  0.38%
247   253          332      1   0.3%
347   373          795      2  0.25%
335   361          400      1  0.25%
117   118         3074      7  0.23%
329   355          885      2  0.23%
132   133         3288      7  0.21%
163   164         3346      7  0.21%

# Basic Bidding Strategies

In [24]:
#calculating constant bid stategy

def constant_bidding(bid):
    impression = 0.0
    clicks = 0
    cost = 0.0
    budget = 2500000 # 1/10th budget of 25,000,000

    
    for click, pay_price in validation[['click','payprice']].values:
            if bid > pay_price:
                impression += 1.0
                clicks += click
                cost += pay_price
            if cost >= budget:
                break
    return impression, clicks, cost

bids = pd.DataFrame()
bids['constants'] = [10,25,50,100,150,200,250,300]

imp = []
clk = []
costs = []
for i in bids['constants']:
    [imps, clicks, cost] = constant_bidding(i)
    imp.append(imps)
    clk.append(clicks)
    costs.append(cost)
bids['impression_won'] = imp
bids['clicks'] = clk
bids['cost'] = costs
bids['CTR'] = (bids.clicks/bids.impression_won * 100).round(2).astype(str)
bids['CPM'] = (bids.cost/bids.impression_won * 1000 ).round(2).astype(str)
bids['CPC'] = (bids.cost/bids.clicks).round(2).astype(str)

In [25]:
bids.sort_values("CTR",ascending = False)

   constants  impression_won  clicks       cost   CTR       CPM       CPC
7        300         31184.0      36  2500043.0  0.12   80170.7  69445.64
6        250         32972.0      35  2500055.0  0.11  75823.58  71430.14
5        200         36988.0      38  2500055.0   0.1  67590.98  65790.92
4        150         42605.0      37  2500093.0  0.09  58680.74  67570.08
3        100         50732.0      43  2500072.0  0.08  49279.98  58141.21
0         10         13364.0       8    76078.0  0.06   5692.76   9509.75
2         50         99058.0      40  2404697.0  0.04  24275.65  60117.42
1         25         56765.0      18   862288.0  0.03  15190.49  47904.89

In [16]:
#calculate random bids from a list of bids

from random import randrange

def random_bid(bid):
    impression = 0.0
    clicks = 0
    cost = 0.0
    budget = 2500000 # 1/10th budget of 25,000,000
    bid = randrange(0,bid)

    
    for click, pay_price in validation[['click','payprice']].values:
            if bid > pay_price:
                impression += 1.0
                clicks += click
                cost += pay_price
            if cost >= budget:
                break
    return impression, clicks, cost,bid

bids = pd.DataFrame()

bids['random'] = [10,25,50,100,150,200,250,300]

imp = []
clk = []
costs = []
true_random_bid = []
for i in bids['random']:
    [imps, clicks, cost,bid] = random_bid(i)
    imp.append(imps)
    clk.append(clicks)
    costs.append(cost)
    true_random_bid.append(bid)
bids['true_bid']=true_random_bid
bids['impression_won'] = imp
bids['clicks'] = clk
bids['cost'] = costs
bids['CTR'] = (bids.clicks/bids.impression_won * 100).round(2).astype(str)
bids['CPM'] = (bids.cost/bids.impression_won * 1000).round(2).astype(str)
bids['CPC'] = (bids.cost/bids.clicks).round(2).astype(str)

In [17]:
bids.sort_values("CTR",ascending= False)

,random,true_bid,impression_won,clicks,cost,CTR,CPM,CPC
5,200,181,38348.0,38,2500055.0,0.1,65193.88,65790.92
6,250,178,38789.0,39,2500014.0,0.1,64451.62,64102.92
7,300,122,46740.0,44,2500030.0,0.09,53488.02,56818.86
4,150,8,10850.0,8,54653.0,0.07,5037.14,6831.62
3,100,17,26289.0,11,241850.0,0.04,9199.67,21986.36
2,50,33,73154.0,23,1342863.0,0.03,18356.66,58385.35
0,10,6,7646.0,1,33986.0,0.01,4444.94,33986.0
1,25,2,360.0,0,289.0,0.0,802.78,inf

In [26]:
bids.sort_values("clicks",ascending= False)

   constants  impression_won  clicks       cost   CTR       CPM       CPC
3        100         50732.0      43  2500072.0  0.08  49279.98  58141.21
2         50         99058.0      40  2404697.0  0.04  24275.65  60117.42
5        200         36988.0      38  2500055.0   0.1  67590.98  65790.92
4        150         42605.0      37  2500093.0  0.09  58680.74  67570.08
7        300         31184.0      36  2500043.0  0.12   80170.7  69445.64
6        250         32972.0      35  2500055.0  0.11  75823.58  71430.14
1         25         56765.0      18   862288.0  0.03  15190.49  47904.89
0         10         13364.0       8    76078.0  0.06   5692.76   9509.75